import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Navbar from "../components/Navbar";
import { 
  Bell, 
  AlertTriangle, 
  CloudLightning, 
  ShieldAlert, 
  Anchor, 
  Search, 
  Filter, 
  Plus, 
  Trash2,
  Navigation,
  CheckCircle,
  Zap,
  Info
} from "lucide-react";

const alertTypes = ["All", "High Risk Route", "Congestion Alert", "Weather Alert", "Port Delay Alert"];
const alertMockSuggestions = [
  {
    type: "High Risk Route",
    title: "Vessel Piracy Volatility Alert",
    message: "High risk warning raised for East Africa lanes due to localized threat parameters.",
    severity: "CRITICAL",
    port: "Mombasa",
    action: "Request maritime military escort support or steer 200 nautical miles south."
  },
  {
    type: "Congestion Alert",
    title: "Singapore Cargo Backlog Warning",
    message: "Berthing queue delays exceeded 72 hours for international container ships.",
    severity: "CRITICAL",
    port: "Keppel - (East Singapore)",
    action: "Redirect immediate transshipment cargos to alternate ports in Malaysia."
  },
  {
    type: "Weather Alert",
    title: "North Atlantic Gale Storm Warning",
    message: "Atmospheric depression creating wave swells exceeding 8 meters on Rotterdam lane.",
    severity: "CRITICAL",
    port: "Rotterdam",
    action: "Delay voyages exiting North America E Coast by 36 hours to permit storm clearance."
  },
  {
    type: "Port Delay Alert",
    title: "Port Customs Labor Action Delay",
    message: "Customs processing slows in New York Harbor owing to technical system updates.",
    severity: "WARNING",
    port: "New York City",
    action: "Prepare pre-clearance documents via digital customs platform to bypass queue."
  }
];

function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [search, setSearch] = useState("");
  const [filterType, setFilterType] = useState("All");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch live alerts generated by route-history from stats endpoint
    fetch("http://127.0.0.1:5000/dashboard-stats")
      .then((res) => res.json())
      .then((data) => {
        if (data && data.recent_alerts && data.recent_alerts.length > 0) {
          const fetchedAlerts = data.recent_alerts.map((a, idx) => ({
            id: a.id || `live-alert-${idx}`,
            type: a.type || "High Risk Route",
            title: a.title || "Maritime Security Volatility",
            message: a.message || "Route volatility alert detected.",
            severity: a.severity || "CRITICAL",
            time: a.time || "Just now",
            port: a.port || "International waters",
            action: a.action || "Activate rerouting algorithms."
          }));
          setAlerts(fetchedAlerts);
        } else {
          // Starts completely empty if no history voyages are in the database!
          setAlerts([]);
        }
      })
      .catch((err) => {
        console.error("Error loading alerts:", err);
        setAlerts([]);
      })
      .finally(() => setLoading(false));
  }, []);

  const simulateAlert = () => {
    const randomTemplate = alertMockSuggestions[Math.floor(Math.random() * alertMockSuggestions.length)];
    const newAlert = {
      id: `sim-alert-${Date.now()}`,
      ...randomTemplate,
      time: "Just now",
    };
    setAlerts([newAlert, ...alerts]);
  };

  const removeAlert = (id) => {
    setAlerts(alerts.filter((a) => a.id !== id));
  };

  const clearAll = () => {
    setAlerts([]);
  };

  const filteredAlerts = alerts.filter((alert) => {
    const matchesSearch =
      alert.title.toLowerCase().includes(search.toLowerCase()) ||
      alert.message.toLowerCase().includes(search.toLowerCase()) ||
      alert.port.toLowerCase().includes(search.toLowerCase());
    const matchesFilter = filterType === "All" || alert.type === filterType;
    return matchesSearch && matchesFilter;
  });

  const isAlertsEmpty = alerts.length === 0;

  return (
    <div className="flex-1 p-7 overflow-y-auto bg-[#081028] text-white">
      {/* Navbar */}
      <Navbar />

      <div className="grid grid-cols-4 gap-6 mt-8">
        
        {/* Left Side: Stats & Disruption simulator */}
        <div className="col-span-1 space-y-6">
          <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-3xl p-6 shadow-[0_0_30px_rgba(0,0,0,0.3)]">
            <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
              <Bell size={22} className="text-blue-400 animate-pulse" />
              Disruption Center
            </h2>
            <p className="text-gray-400 text-xs mb-5 leading-relaxed">
              View live operational feeds tracking storm fronts, port dwel times, labor strikes, and regional piracy threats.
            </p>

            <div className="space-y-4">
              <button
                onClick={simulateAlert}
                className="w-full bg-blue-600 hover:bg-blue-700 py-3.5 rounded-2xl font-bold transition-all duration-300 flex items-center justify-center gap-2 cursor-pointer text-sm shadow-md"
              >
                <Plus size={16} />
                Simulate Disruption
              </button>
              
              <button
                onClick={clearAll}
                disabled={alerts.length === 0}
                className="w-full bg-white/5 hover:bg-red-500/20 hover:text-red-400 border border-white/10 py-3 rounded-2xl font-bold transition-all duration-300 flex items-center justify-center gap-2 cursor-pointer text-sm disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Trash2 size={16} />
                Purge Alert Feed
              </button>
            </div>
          </div>

          {/* Quick Alert Stats */}
          <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-3xl p-6 shadow-[0_0_30px_rgba(0,0,0,0.3)] space-y-4">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider">Alert Summary Metrics</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl text-center">
                <span className="text-[10px] text-red-300 uppercase font-bold">Critical</span>
                <h4 className="text-2xl font-extrabold text-red-400 mt-1">
                  {alerts.filter((a) => a.severity === "CRITICAL").length}
                </h4>
              </div>
              <div className="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-2xl text-center">
                <span className="text-[10px] text-yellow-300 uppercase font-bold">Warning</span>
                <h4 className="text-2xl font-extrabold text-yellow-400 mt-1">
                  {alerts.filter((a) => a.severity === "WARNING").length}
                </h4>
              </div>
            </div>
          </div>
        </div>

        {/* Right Side: Alerts Feed */}
        <div className="col-span-3 space-y-6">
          {isAlertsEmpty ? (
            /* STUNNING GLASSMORPHISM BLANK STATE IF NO INCIDENTS IN CORRIDORS */
            <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-3xl p-12 text-center text-gray-400 min-h-[420px] flex flex-col justify-center items-center shadow-[0_0_50px_rgba(0,0,0,0.3)]">
              <Bell size={80} className="mx-auto text-gray-600 mb-6 animate-bounce" />
              <h3 className="font-extrabold text-3xl text-white mb-3">No active maritime alerts recorded.</h3>
              <p className="text-sm max-w-md mx-auto leading-relaxed">
                Simulate shipping corridors on the Dashboard Waterway Risk Simulator to dynamically trigger gale force warnings, terminal capacity alerts, or security updates.
              </p>
            </div>
          ) : (
            <>
              {/* Search & Filters */}
              <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-3xl p-4 shadow-[0_0_30px_rgba(0,0,0,0.3)] flex flex-wrap gap-4 items-center justify-between">
                <div className="flex items-center gap-3 bg-black/25 border border-white/10 px-4 py-2.5 rounded-2xl w-80">
                  <Search size={18} className="text-gray-400" />
                  <input
                    type="text"
                    placeholder="Search alerts, port names, actions..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="bg-transparent outline-none text-sm text-white w-full"
                  />
                </div>

                <div className="flex items-center gap-2">
                  <Filter size={16} className="text-gray-400" />
                  <div className="flex bg-black/25 rounded-2xl p-1 border border-white/5">
                    {alertTypes.map((type) => (
                      <button
                        key={type}
                        onClick={() => setFilterType(type)}
                        className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all duration-350 cursor-pointer ${
                          filterType === type ? "bg-blue-600 text-white shadow-md" : "text-gray-400 hover:text-white"
                        }`}
                      >
                        {type === "All" ? "All Feeds" : type.split(" ")[0]}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Alert Feed Cards */}
              <div className="space-y-4">
                <AnimatePresence initial={false}>
                  {filteredAlerts.length === 0 ? (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="bg-white/5 border border-white/10 rounded-3xl p-12 text-center text-gray-400"
                    >
                      <Bell size={48} className="mx-auto text-gray-600 mb-3" />
                      <p className="font-semibold text-lg text-white">All Channels Operational</p>
                      <p className="text-sm mt-1">No disruptions match your filters.</p>
                    </motion.div>
                  ) : (
                    filteredAlerts.map((alert) => {
                      let badgeColor = "bg-yellow-500/20 text-yellow-400 border-yellow-500/30";
                      let icon = <AlertTriangle className="text-yellow-400" size={20} />;
                      
                      if (alert.severity === "CRITICAL") {
                        badgeColor = "bg-red-500/20 text-red-400 border-red-500/30";
                        icon = <ShieldAlert className="text-red-400 animate-pulse" size={20} />;
                      }
                      if (alert.type === "Weather Alert") {
                        icon = <CloudLightning className={alert.severity === "CRITICAL" ? "text-red-400" : "text-yellow-400"} size={20} />;
                      }
                      if (alert.type === "Port Delay Alert") {
                        icon = <Anchor className={alert.severity === "CRITICAL" ? "text-red-400" : "text-yellow-400"} size={20} />;
                      }

                      return (
                        <motion.div
                          key={alert.id}
                          initial={{ opacity: 0, y: 20 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, x: -100 }}
                          transition={{ duration: 0.25 }}
                          className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-3xl p-5 shadow-[0_0_30px_rgba(0,0,0,0.35)] flex flex-col gap-4 hover:scale-[1.005] transition-transform duration-300"
                        >
                          <div className="flex items-start justify-between">
                            <div className="flex items-center gap-4">
                              <div className={`w-12 h-12 rounded-2xl flex items-center justify-center ${badgeColor.split(" ")[0]} border ${badgeColor.split(" ")[2]}`}>
                                {icon}
                              </div>
                              
                              <div className="space-y-1">
                                <div className="flex items-center gap-2 flex-wrap">
                                  <span className="font-extrabold text-white text-base">{alert.title}</span>
                                  <span className="text-gray-500 font-bold text-xs">•</span>
                                  <span className="text-blue-400 text-xs font-mono font-bold">{alert.port}</span>
                                  <span className="text-gray-500 font-bold text-xs">•</span>
                                  <span className="text-gray-400 text-xs">{alert.time}</span>
                                </div>
                                <p className="text-gray-300 text-sm leading-relaxed">{alert.message}</p>
                              </div>
                            </div>

                            <div className="flex items-center gap-3 shrink-0 ml-6">
                              <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-extrabold border uppercase ${badgeColor}`}>
                                {alert.severity}
                              </span>
                              <button
                                onClick={() => removeAlert(alert.id)}
                                className="p-2 hover:bg-red-500/10 text-gray-500 hover:text-red-400 rounded-xl transition cursor-pointer"
                                title="Dismiss Disruption"
                              >
                                <Trash2 size={16} />
                              </button>
                            </div>
                          </div>

                          {alert.action && (
                            <div className="bg-emerald-500/10 border border-emerald-500/15 rounded-2xl p-3 flex items-start gap-2.5 text-xs text-slate-300">
                              <CheckCircle className="text-emerald-400 shrink-0 mt-0.5" size={14} />
                              <div>
                                <span className="text-emerald-400 font-bold uppercase text-[9px] tracking-wider flex items-center gap-1">
                                  <Zap size={10} className="animate-bounce" />
                                  AI Tactical Recommended Action
                                </span>
                                <p className="mt-0.5 font-normal leading-relaxed text-gray-200">{alert.action}</p>
                              </div>
                            </div>
                          )}
                        </motion.div>
                      );
                    })
                  )}
                </AnimatePresence>
              </div>
            </>
          )}
        </div>

      </div>
    </div>
  );
}

export default Alerts;
